/*
Author: Cassie Lewis
https://clewisdev.com
Date: April 2023
*/

/****** VARIABLES ******/

//TODO 
//!CREATE ARRAY TO HOLD TASK DATA
/*
Restaurant app data is an array that contains an object for each food item.
name, ingredients, price, emoji, id
This app data: task, price, id
*/
//? How does the price be set to the value of the dropdown input field?

//TODO 
//!ADD BUTTON VARIABLE
//!INPUT VARIABLES

//TODO 
//!REMOVE BUTTON VARIABLE

//TODO 
//!SEND INVOICE BUTTON VARIABLE


/****** FUNCTIONS ******/

//TODO 
//!FUNCTION THAT ADDS TASK TO ARRAY
//? .push() method?

//TODO 
//!DISPLAY DATA FROM ARRAY, DISPLAY UPDATES WHEN ARRAY CHANGES
//!CHARGE ONLY ONCE FOR EACH TASK (DON'T ADD DUPLICATES)

//TODO 
//!UPDATE TOTAL AMOUNT EACH TIME A TASK GETS ADDED

//TODO 
//!REMOVE BUTTON REMOVES TASKS FROM LIST AND TOTAL

//TODO 
//!SEND INVOICE BUTTON RESETS FORM AND TOTAL AMOUNT TO $0


/****** EVENT LISTENERS ******/

//TODO 
//!ADD BUTTON ADDS TASK TO ARRAY - EVENT LISTENER

//TODO 
//!REMOVE BUTTON REMOVES TASKS FROM LISTS AND TOTAL - EVENT LISTENER

//TODO
//!SEND INVOICE BUTTON RESETS - EVENT LISTENER